os: linux
dist: focal
language: c
services:
    - docker
git:
    submodules: false
addons:
  apt:
    update: true
    packages:
    - clang-10
    - clang-tools-10
    - bison
    - flex
    - libjson-c-dev
    - autoconf-archive
    - libxen-dev
env:
  global:
    - CC=clang-10
    - CPP=clang-cpp-10
    - CXX=clang++-10
    - INSTALLDIR=$PWD/usr/local/
    - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/usr/local/lib
    - C_INCLUDE_PATH=$PWD/usr/local/include
    - CPLUS_INCLUDE_PATH=$PWD/usr/local/include
    - PKG_CONFIG_PATH="$PWD/usr/local/lib/pkgconfig/"
    - LDFLAGS="-L$PWD/usr/local/lib"
    - CFLAGS="-I$PWD/usr/local/include"

jobs:
    include:

#
# Coverity (broken at the moment on focal with clang-10)
#
    - env:
        - TEST="Coverity"
      addons:
        coverity_scan:
            project:
                name: "$COVERITY_PROJECT_NAME"
                description: "Build submitted via Travis CI"
            notification_email: $COVERITY_NOTIFICATION_EMAIL
            build_command_prepend: "./autogen.sh; ./configure --enable-debug; make clean"
            build_command:   "make"
            branch_pattern: $COVERITY_BRANCH_PATTERN
      before_install:
        - sudo apt-get update
        - sudo apt-get -q -y install bison flex libjson-c-dev autoconf-archive libxen-dev clang-10
        - git submodule update --init libvmi
        - cd libvmi
        - autoreconf -vif
        - ./configure --prefix=${INSTALLDIR} --disable-kvm --disable-file --disable-bareflank --disable-safety-checks
        - make
        - make install
        - cd ..
      script:
        - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

#
# SonarCloud
#
    - env:
        - TEST="SonarCloud"
      addons:
        sonarcloud:
            organization: "drakvuf"
            token: "$SONAR_TOKEN"
      script:
        - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then exit 0; fi'
        - git submodule update --init libvmi
        - cd libvmi
        - autoreconf -vif
        - ./configure --prefix=${INSTALLDIR} --disable-kvm --disable-file --disable-bareflank --disable-safety-checks
        - make
        - make install
        - cd ..
        - ./autogen.sh
        - ./configure --enable-debug
        - build-wrapper-linux-x86-64 --out-dir bw-output make -j2
        - sonar-scanner

