name: deb
on:
  pull_request:
    branches: [ master ]
jobs:
  deb:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        container:
          - "debian:buster"
          - "ubuntu:bionic"
          - "ubuntu:focal"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: deb
        run: |
          sh package/build.sh ${{ matrix.container }}
